name: www.anco.md
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8352299409452826
title: Architectural Glass
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.8478419918101281
  saturation: 0.5796263180673122
  rhythmicContrast: 0.75
purpose: []
